### ISSUE TITLE
Vince's Set-up Test

### ISSUE THREAD

**Issue by Bilgecrank** [Bilgecrank/hindsite#4]
This one is for @vtestagrossa 

Test out your local set-up by creating a branch of your own from this issue, and then getting the project on your local development environment. Add a function to `src/dev-team-funcs.py` that prints a message, push the changes back to here, and make a pull request that I can review.

If we get multiple pull requests at once, we can test out making multiple changes to a single file.

**Comment by vtestagrossa** [comment]
I'll get right on it.

**Comment by vtestagrossa** [comment]
P/R Awaiting approval.

**Comment by Bilgecrank** [comment]
Looking at it now

**Comment by Bilgecrank** [comment]
Done and done, good job
